### ISSUE TITLE
Textual Tweaks -  

### ISSUE THREAD

**Issue by HazardJ** [ErichDylus/Open-Source-Law#4]
Terms" is used but not defined.

"Jurisdiction" section is actually about applicable law.  There should be a dispute resolution section with choice of a path for dispute resolution.  The most important issue in moving from on-chain to off-chain impacts. Also for Hart & Holmström's contract "incompleteness."  There are a number of formulations available as pObs. http://www.commonaccord.org/index.php?action=source&file=S/Index/Dispute.md

**Comment by ErichDylus** [comment]
Thanks, addressed in latest changes. Used JAMS as a dispute resolution placeholder for now, freely replaceable
