### ISSUE TITLE
Tiny point - "Entity" is used instead of [ENTITY]

### ISSUE THREAD

**Issue by HazardJ** [ErichDylus/Open-Source-Law#5]
In the third paragraph of the Remedies section:  "It is solely Entity’s responsibility to ...."   [ENTITY] is used as a parameter to be replaced, but this "Entity" is used as if it was a defined term.  (Nice conceptual difference.) (Seems to be the only place where that happens.

**Comment by ErichDylus** [comment]
Good catch, yes I thought it would be best to parameterize the entity (using [ENTITY]) in this section to draw further attention (and I've just changed the lone "Entity" to the [ENTITY] parameter), but it could just as easily be used as a general "Entity" defined term by editing the recitals/preamble accordingly. Up to the adapter of the form!

**Comment by HazardJ** [comment]
Thanks, yes.  I tweaked your form to make it "[ENTITY]", consistent with the other uses.  Yes, Defined Terms, are often a good way to deal with this rather than doing name substitutions.  In Prose Objects the form can permit both, with the choice being left to the user. The Defined Terms are generally parameterized to make it easy to link to the Definition as a hyperlink.  So the Defined Term can be also be overridden with a specific name if the user wants.
